### ISSUE TITLE
Error at building -- [error] (*:assembly) deduplicate: different file contents found in the following

### ISSUE THREAD

**Issue by jaceklaskowski** [sasha-polev/aerospark#20]
(I couldn't find a way to file the issue in https://github.com/aerospike/aerospark so I'm doing it here so it's not lost.)

When I tried to build aerospark I followed the instructions at https://github.com/aerospike/aerospark#how-to-build, i.e.

```
$ oss # switch to the directory with OSS projects
$ git clone https://github.com/aerospike/aerospike-helper
$ cd aerospike-helper/java
$ mvn clean install -DskipTests
```

It finished successfully.

```
$ oss
$ git clone https://github.com/aerospike/aerospark.git
$ cd aerospark
$ sbt 'set test in assembly := {}' clean assembly
```

That failed due to the following errors:

```
[error] 1 error was encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/Users/jacek/dev/oss/aerospark/lib/aerospike-helper-java-1.0.6.jar:META-INF/maven/com.aerospike/aerospike-client/pom.xml
/Users/jacek/.m2/repository/com/aerospike/aerospike-helper-java/1.0.6/aerospike-helper-java-1.0.6.jar:META-INF/maven/com.aerospike/aerospike-client/pom.xml
/Users/jacek/.ivy2/cache/com.aerospike/aerospike-client/jars/aerospike-client-3.3.0.jar:META-INF/maven/com.aerospike/aerospike-client/pom.xml
    at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
    at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
    at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
    at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
    at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
    at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
    at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
    at sbtassembly.Assembly$.apply(Assembly.scala:83)
    at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
    at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /Users/jacek/dev/oss/aerospark/lib/aerospike-helper-java-1.0.6.jar:META-INF/maven/com.aerospike/aerospike-client/pom.xml
[error] /Users/jacek/.m2/repository/com/aerospike/aerospike-helper-java/1.0.6/aerospike-helper-java-1.0.6.jar:META-INF/maven/com.aerospike/aerospike-client/pom.xml
[error] /Users/jacek/.ivy2/cache/com.aerospike/aerospike-client/jars/aerospike-client-3.3.0.jar:META-INF/maven/com.aerospike/aerospike-client/pom.xml
[error] Total time: 43 s, completed Oct 22, 2016 12:44:42 AM
```

Any idea how to fix it?

**Comment by thefishermanhacker** [comment]
Hi,
Its Sasi :).
You should update sbt-assembly.
Try the following: 
https://github.com/sbt/sbt-assembly#excluding-jars-and-files
Or this one: 
http://stackoverflow.com/questions/25144484/sbt-assembly-deduplication-found-error

Sasi

**Comment by jaceklaskowski** [comment]
My thinking is like this: if a pull request is needed to fix it then this is a real issue/bug since the project can't be built. Is that what others are experiencing too?
